steps:
  # Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "gcr.io/$PROJECT_ID/employment-match-final:$COMMIT_SHA",
        ".",
      ]

  # Push the container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/employment-match-final:$COMMIT_SHA"]

  # Deploy container image to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "employment-match-final"
      - "--image"
      - "gcr.io/$PROJECT_ID/employment-match-final:$COMMIT_SHA"
      - "--region"
      - "europe-north1"
      - "--platform"
      - "managed"
      - "--allow-unauthenticated"
      - "--memory"
      - "2Gi"
      - "--cpu"
      - "2"
      - "--max-instances"
      - "10"
      - "--timeout"
      - "300"
      - "--set-env-vars"
      - "DATABASE_URL=${_DATABASE_URL},SECRET_KEY=${_SECRET_KEY},GEMINI_API_KEY=${_GEMINI_API_KEY}"

# Store images in Google Container Registry
images:
  - "gcr.io/$PROJECT_ID/employment-match-final:$COMMIT_SHA"

# Substitution variables (set these in Cloud Build triggers)
substitutions:
  _DATABASE_URL: "postgresql://neondb_owner:npg_ZoB1Unqpc3rJ@ep-red-salad-a20vuj1d.eu-central-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require"
  _SECRET_KEY: "OwCZ_QC5xaHZJ6m5B2S6F_WsFydovnXGJxWSt5r120Q"
  _GEMINI_API_KEY: "AIzaSyCSzIna3eChAypUuPeAJAtWU9YCZE0Nl_8"
